library(systr)
library(tidyverse)
library(scales)
library(corrr)
df = readRDS("./data/original_data/sdgs.rds")
meta = readRDS("./data/original_data/sdg_meta.rds")
newscale = c(1,10)
systr_setup(df, meta, newscale)
corpus = readRDS("02-scaled_db.rds") %>% filter(geocode == "MEX")
systr_granger(corpus)